# Default recipe to display available commands.
_:
  @just --list

# Format and lint the package using ruff.
lint:
  ruff format
  ruff check --fix

# Same as `lint`, but doesn't make any formatting changes.
lint-check:
  ruff format --check
  ruff check

# Run the test suite.
test:
  pytest --log-cli-level=INFO

# Run tests with coverage report.
test-cov:
  pytest --cov={{cookiecutter.package_name}} --cov-report=term-missing --cov-fail-under=90

# Run static type checker.
typecheck:
  pyright

# Build the documentation using Zensical.
docs: 
  zensical build
